name: recombee_client
description: Recombee API Wrapper.
version: 1.0.0
homepage: https://github.com/indmind/recombee-client

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  http: ^1.1.0
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.17.10
